
name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Go environment
      uses: actions/setup-go@v5.3.0
      with:
        go-version: stable
    
    - name: Build and Test
      run: ./run_tests.sh
      shell: bash
